### ISSUE TITLE
Could we should we infer requirements if missing?

### ISSUE THREAD

**Issue by Rabscuttler** [treebeardtech/treebeard#14]
A requirements generator could infer environment requirements from notebook cell imports.
But this could be the wrong path to take.

Should we prioritise robustness or ease of use?

**Comment by alex-remedios** [comment]
My view is that we shouldn't prioritise this because
(a) We support different package managers (requirements.txt, pipfile, environment.yml) equally well currently and I'm not sure which we would be best off autogenerating
(b) it discourages opening and manually reading/writing these dependency files which is necessary for fixing a long tail of issues which remain with dependency management
(c) Both robustness and ease of use are important, but I'm not that confident that auto-inferring requirements will be much easier to use...happy to debate this
