### ISSUE TITLE
Custom paths for environment.yml (and potentially others?)

### ISSUE THREAD

**Issue by jaimergp** [treebeardtech/treebeard#41]
As discussed in [Gitter](https://gitter.im/treebeardtech/community?at=5f8f047b3d172d78b388a7e7):

**Is your feature request related to a problem? Please describe.**

In an attempt to have less noisy repo roots, the [MolSSI cookiecutter template](https://github.com/MolSSI/cookiecutter-cms/) suggests having some configuration files under [`devtools/`](https://github.com/volkamerlab/TeachOpenCADD/tree/reviews/devtools/conda-envs). This is the case for `environment.yml`.
 
**Describe the solution you'd like**

I'd like to specify a non-default path in `treebeard.yml` that points to the custom location. Something like `conda-environment-file` could work.

**Describe alternatives you've considered**

I am symlinking `environment.yml -> devtools/conda-envs/test_env.yml`, but that defeats the purpose of reducing the clutter at the repo root.

**Additional context**

I guess users would expect other requirement files like pip's to have their custom location counterparts too (`pip-requirements-file`, etc).

**Comment by alex-remedios** [comment]
Thanks for writing this up Jaime,

I have just pushed a solution to master based on your input:

Rather than using the Treebeard yaml file, I have started using gh action inputs for parameters. This allows different values for different invocations in the same repository.

`req-file-path`, as seen used in this [integ test](https://github.com/treebeardtech/treebeard/blob/master/.github/workflows/action_integration_test.yml#L57) will map a requirements file of your choice into the bundle submitted to repo2docker (see [logic](https://github.com/treebeardtech/treebeard/blob/master/treebeard-lib/treebeard/notebooks/commands.py#L217-L231))

As you are using the master version of this action in your action you should be able to pass this parameter now, so please give me feedback on how it is going

**Comment by alex-remedios** [comment]
Feel free to reopen if anything's wrong
